version: "3.5"

services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: teste@teste.com
      PGADMIN_DEFAULT_PASSWORD: teste
    ports:
      - "5050:80"
      
  api01: &api
    # image: bigodex/rinha-api-2024-q1:latest
    build: ./RinhaBackEnd2024Q1/
    hostname: rinha-api
    environment:
      - ConnectionStrings__DefaultConnection = "Host=db;Pooling=true;Database=rinha;User Id=postgres;Password=Postgres2024!"
    ports:
      - "8081:80"
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "120MB"

  # api02:
  #   <<: *api
  #   ports:
  #     - "8082:80"
  
  # nginx:
  #   image: nginx:latest
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - api01
  #     - api02
  #   ports:
  #     - "9999:9999"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "0.45"
  #         memory: "40MB"

  postgres:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=Postgres2024!
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    command: 'postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -c max_connections=1000 -c shared_buffers=128MB -c synchronous_commit=off -c fsync=off -c full_page_writes=off' 
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "270MB"

networks:
  default:
    driver: bridge
    name: rinha-network