
-- START TRANSACTION;

-- CREATE TABLE public.cliente (
--     id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
--     limite integer NOT NULL,
--     saldo integer NOT NULL,
--     CONSTRAINT "PK_cliente" PRIMARY KEY (id)
-- );

-- CREATE TABLE public.Transacoes (
--     "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
--     valor integer NOT NULL,
--     tipo character(1) COLLATE pg_catalog."default" NOT NULL,
--     descricao character varying(10) COLLATE pg_catalog."default" NOT NULL,
--     realizada_em timestamp without time zone NOT NULL,
--     "IdCliente" integer NOT NULL,
--     CONSTRAINT "PK_Transacoes" PRIMARY KEY ("Id"),
--     CONSTRAINT "FK_Transacoes_cliente_IdCliente" FOREIGN KEY ("IdCliente")
--         REFERENCES public.cliente (id) MATCH SIMPLE
--         ON UPDATE NO ACTION
--         ON DELETE CASCADE
-- );


-- CREATE INDEX IF NOT EXISTS "IX_Transacoes_IdCliente"
--     ON public."Transacoes" USING btree
--     ("IdCliente" ASC NULLS LAST);


-- COMMIT;



-- INSERT INTO public.cliente (limite, saldo) VALUES
-- (100000, 0),
-- (80000, 0),
-- (1000000, 0),
-- (10000000, 0),
-- (500000, 0);

