// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RinhaBackEnd2024Q1.Data;

#nullable disable

namespace RinhaBackEnd2024Q1.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240403000312_FistMigration")]
    partial class FistMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RinhaBackEnd2024Q1.Model.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Limite")
                        .HasColumnType("integer")
                        .HasColumnName("limite");

                    b.Property<int>("Saldo")
                        .HasColumnType("integer")
                        .HasColumnName("saldo");

                    b.HasKey("Id");

                    b.ToTable("cliente");
                });

            modelBuilder.Entity("RinhaBackEnd2024Q1.Model.Transacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("descricao");

                    b.Property<int>("IdCliente")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Realizada_em")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("realizada_em");

                    b.Property<char>("Tipo")
                        .HasColumnType("character(1)")
                        .HasColumnName("tipo");

                    b.Property<int>("valor")
                        .HasColumnType("integer")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.ToTable("Transacoes");
                });

            modelBuilder.Entity("RinhaBackEnd2024Q1.Model.Transacao", b =>
                {
                    b.HasOne("RinhaBackEnd2024Q1.Model.Cliente", "Cliente")
                        .WithMany("Transacoes")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("RinhaBackEnd2024Q1.Model.Cliente", b =>
                {
                    b.Navigation("Transacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
